apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: truify-openrouter
  annotations:
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/cpu-throttling: "false"
    run.googleapis.com/startup-cpu-boost: "true"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
        run.googleapis.com/memory: 8Gi
        run.googleapis.com/cpu: 2
    spec:
      containerConcurrency: 1
      timeoutSeconds: 3600
      containers:
      - image: gcr.io/PROJECT_ID/truify-openrouter
        ports:
        - containerPort: 8501
        env:
        - name: GMAIL_USER
          valueFrom:
            secretKeyRef:
              name: gmail-secret
              key: user
        - name: GMAIL_APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gmail-password
              key: password
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: openrouter-secret
              key: api_key
        resources:
          limits:
            memory: 8Gi
            cpu: "2"
