version: '3.8'

services:
  truify:
    build: .
    ports:
      - "8501:8501"
    environment:
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    volumes:
      - ./data:/app/data
      - ./email.csv:/app/email.csv
      - ./users.csv:/app/users.csv
    restart: unless-stopped 